import javax.swing.JOptionPane;
import oru.inf.InfException;
/*
 *
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author willi
 */
public class InstallningarAgent extends javax.swing.JFrame {

    /**
     * Creates new form InstallningarAgent
     */
    public InstallningarAgent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitel = new javax.swing.JLabel();
        lbNamn = new javax.swing.JLabel();
        lbTelefon = new javax.swing.JLabel();
        lbEpost = new javax.swing.JLabel();
        lbLösenord = new javax.swing.JLabel();
        btnAndraLosen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitel.setText("Inställningar");

        lbNamn.setText("jLabel1");
        //hämtar agent namnet
        try{
            String getNamn = Start.idb.fetchSingle("SELECT NAMN from agent where Epost ='" + Start.epost + "'");
            lbNamn.setText(getNamn);
        }
        catch(InfException e)
        {
            System.out.println (e);
        }

        lbTelefon.setText("jLabel2");
        //Hämta telefonnummer från databasen
        try{
            String getTelefon = Start.idb.fetchSingle("SELECT Telefon from agent where Epost ='" + Start.epost + "'");
            lbTelefon.setText(getTelefon);
        }
        catch(InfException e)
        {
            System.out.println (e);
        }

        lbEpost.setText("jLabel3");
        //Hämta epost
        try{
            String getEpost = Start.idb.fetchSingle("SELECT Epost from agent where Epost ='" + Start.epost + "'");
            lbEpost.setText(getEpost);
        }
        catch(InfException e)
        {
            System.out.println (e);
        }

        lbLösenord.setText("jLabel4");
        //Hämta lösenord
        try{
            String getLosenord = Start.idb.fetchSingle("SELECT Losenord from agent where Epost ='" + Start.epost + "'");
            lbLösenord.setText(getLosenord);
        }
        catch(InfException e)
        {
            System.out.println (e);
        }

        btnAndraLosen.setText("Ändra Lösenord");
        btnAndraLosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAndraLosenMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(lbTitel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNamn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(lbTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbEpost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbLösenord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAndraLosen)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitel)
                .addGap(31, 31, 31)
                .addComponent(lbNamn)
                .addGap(27, 27, 27)
                .addComponent(lbTelefon)
                .addGap(26, 26, 26)
                .addComponent(lbEpost)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLösenord)
                    .addComponent(btnAndraLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAndraLosenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAndraLosenMousePressed
        
    }//GEN-LAST:event_btnAndraLosenMousePressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraLosen;
    private javax.swing.JLabel lbEpost;
    private javax.swing.JLabel lbLösenord;
    private javax.swing.JLabel lbNamn;
    private javax.swing.JLabel lbTelefon;
    private javax.swing.JLabel lbTitel;
    // End of variables declaration//GEN-END:variables
}
