
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfException;
import java.sql.SQLException;





/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class TaBortUtrustning extends javax.swing.JFrame {

    /**
     * Creates new form TaBortUtrustning
     */
    public TaBortUtrustning() {
        initComponents();
        fyllComboBoxUtrustning();
    }

    
    private void fyllComboBoxUtrustning() {

        try {

            ArrayList<HashMap<String, String>> utrustningsLista = Start.idb.fetchRows("SELECT Utrustnings_ID, Benamning FROM utrustning");
            jComboBox1.removeAllItems();
            for (int i = 0; i < utrustningsLista.size(); i++) {
                
                String utrustningsId = utrustningsLista.get(i).get("Utrustnings_ID");
                String benamning = utrustningsLista.get(i).get("Benamning");

                String utrustningCombo = utrustningsId + ": " + benamning;
                jComboBox1.addItem(utrustningCombo);
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTxt = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnTillbaka = new javax.swing.JButton();
        btnVerkstall1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Ta bort utrustning ur systemet");

        lblTxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTxt.setText("Välj utrustning att ta bort:");

        btnTillbaka.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTillbaka.setForeground(new java.awt.Color(255, 0, 51));
        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTillbakaMousePressed(evt);
            }
        });
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnVerkstall1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVerkstall1.setText("Verkställ");
        btnVerkstall1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerkstall1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblTxt)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(btnVerkstall1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(464, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(289, Short.MAX_VALUE)
                    .addComponent(btnVerkstall1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(167, 167, 167)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // TODO add your handling code here:

        try {

            //Hämtar valt objekt från combon
            String valdUtrustningObjektet = (String) jComboBox1.getSelectedItem();

            //Checkar om nåt objekt är valt eller inte
            if (valdUtrustningObjektet != null) {
                // Extrahera Utrustnings_ID från den valda strängen

                //Splittar strängen vid ":" så id blir ensammare än mig. Det gör att det returnerar
                //en array med 2 delar, ID o Benamning. [0] tar första delen (ID). 
                //Trim tar bort mellanslag runt ID (Det var bra om man gjorde det ok?)
                //Så valdUtrustningObjektet är t.ex. 99: SuperblastMegaSonic som kommer ge
                //utrustningsID 99. Frågan byggs sedan på bara Id:t för o ta bort valda raden.
                //Integer.parseInt konverterar en sträng till int
                int utrustningsId = Integer.parseInt(valdUtrustningObjektet.split(":")[0].trim());

                String fraga = "DELETE FROM utrustning WHERE Utrustnings_ID = " + utrustningsId;

                try {
                    
                    //Delete metoden anropas från Start.idb för o ta bort raden
                    //fraga = (fraga där uppe)
                    Start.idb.delete(fraga);
                    JOptionPane.showMessageDialog(this, "Utrustningen har tagits bort.", "Meddelande", JOptionPane.INFORMATION_MESSAGE);
                    //Uppdaterar combon efter man tryckt verkställ
                    fyllComboBoxUtrustning();
                    
                    //Detta behövs för o fånga upp sql fel  
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Ett fel uppstod vid borttagning av utrustning.", "Fel", JOptionPane.ERROR_MESSAGE);
                }
            }
            
            //Denna behövdes för att första try skulle få nåt catch. Headless.. fick jag som förfrågan om man ville ha så ja ba tog de
        } catch (HeadlessException | NumberFormatException e) { 
            // För att skriva ut felet till konsolen (går att ta bort om du inte behöver det)
            JOptionPane.showMessageDialog(this, "Ett oväntat fel inträffade.", "Fel", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnVerkstall1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerkstall1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerkstall1ActionPerformed

    private void btnTillbakaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTillbakaMousePressed
        dispose();
        new MenyValAdmin().setVisible(true);
    }//GEN-LAST:event_btnTillbakaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaBortUtrustning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnVerkstall1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTxt;
    // End of variables declaration//GEN-END:variables
}
